### PR TITLE
50 add error handling for missing and invalid tools from datawolf

### LINKED ISSUE #50: Add error handling for missing tools from dependency graph
Right now we expect that the datawolf will only have tools with the latest names as in pyincore but if there is a tool that doesn't comply with the latest names in pyincore frontend will break. We need to rectify this.

### PR DESCRIPTION
**Pull request by Rashmil-1999**
This PR adds error handling page for missing dependency graph and/or invalid tools used in a workflow and empty workflow files. This means all the workflow in the dev datawolf instance will be invalid since they use old tools. try this id for getting to the invalid workflow page 05e5ac18-c202-4a8b-973d-01afcae20b14

http://localhost:3000/workflow-editor/05e5ac18-c202-4a8b-973d-01afcae20b14

### CODE REVIEW

**Comment by ywkim312** [comment]
I ran the PR against dev and click the link above and I only see the message saying "Loading" then nothing happens.

**Comment by ywkim312** [comment]
Same thing happens using tst. Maybe I am doing something wrong?

**Comment by Rashmil-1999** [comment]
Screenshot 2024-11-20 at 10 40 01 AM
This is what you should essentially see....

**Review by ywkim312 — APPROVED** [review]
The result was as what was explained

**Pull request merged**
