### PR TITLE
16 create workflow execution summary page

### LINKED ISSUE #7: Create summary nodes for Workflow executions page
We need to create a simplified node that just has 1 input and 1 output handle that gives a gist of what analysis connects to what. This node is to be used on the workflow executions page from project page when a user clicks on a workflow to see more details.

### LINKED ISSUE #16: Create workflow execution summary page.
We need to create a summary page for executions where we can see a minimized workflow graph and all the previous executions. If there are no executions, we can still allow the user to edit the workflow and hence, the edit workflow button would still be available. Otherwise, it won't. We still need to have a button that redirects the user to the execution page to set new parameters and submit that execution. Here are some screenshots for reference but these are not very accurate so feel free to use them just as a guide.
Screenshot 2024-09-19 at 4 19 13 PM
Screenshot 2024-09-19 at 4 19 34 PM
Screenshot 2024-09-19 at 4 19 56 PM

### PR DESCRIPTION
**Pull request by Rashmil-1999**
This PR adds a workflow execution summary component.

To test, use the test.in-core.org hostname as it has the new datawolf with right tools to be able to parse the workflow and create a summary workflow.
Screenshot 2024-11-20 at 9 01 18 AM
Screenshot 2024-11-20 at 9 01 04 AM
Screenshot 2024-11-20 at 9 00 39 AM

### CODE REVIEW

**Comment by longshuicy** [comment]
@Rashmil-1999 could you give me an example workflow that I can test with? 
Also I merged a bunch of things so now there are merge conflicts need to be resolved.

**Comment by Rashmil-1999** [comment]
Ahh yes. You can test it with tst instance, there is a project with just 2 workflows one with execution and one without. the other project's workflow ids might be invalid so it would not work. I think after I merge develop here, the page with invalid ids should appear...

**Comment by Rashmil-1999** [comment]
I think everything should work now.

**Review by longshuicy — APPROVED** [review]
Test it works well.

**Pull request merged**
