### PR TITLE
18 create visualization component

### LINKED ISSUE #9: Add Maplibre
To show map and its related data, we need to add maplibre package and create a Map component.

### LINKED ISSUE #18: Create Visualization component
On the project page, we are going to add a visualization component that would need a few things:

- [ ] Add backend support for storing visualizations per project. We can discuss what needs to be implemented later.
- [ ] Add options to other dataset viewing components that allow the user to "add" the dataset to an existing or create and add to a new visualization.

The visualization component can lie at the bottom and show user's created visualizations or give them to create an empty visualization.

Screenshot 2024-09-20 at 1 38 52 PM

### LINKED ISSUE #19: Add "Add to Visualization" option/button
When the Visualization component is added and execution page is at a state to support this feature, we need to add this capability for a user to be able to click a button on one of the output nodes and add that result, if possible, to an existing visualization that a user owns or can create on the spot.

### PR DESCRIPTION
**Pull request by longshuicy**
This PR: 
- Create new visualizations
  - Can create from the "create new visualization" button
  - Alternatively, can create from the "add to visualizations" interface
- Add hazard/dataset to visualizations 
- Bounding Box setting is optional
- Style selection is optional

**KNOWN BUGS**
- Cannot add to a newly created layer. Will be fix in the backend PR: https://github.com/IN-CORE/incore-services/issues/331
- Listing all the visualizations to add causing pagination issues. Need to find a way to list all

image
image
image
image
image

### CODE REVIEW

**Comment by Rashmil-1999** [comment]
Could you please add a changelog entry?

**Comment by Rashmil-1999** [comment]
I think the conflict speaks about the file https://github.com/IN-CORE/incore-studio/pull/53/files#diff-05a7a39740391d6605b339da8ad220f20c066abb5bccb3d6a40ee49471f98f6b 

Which we don't need.

**Comment by Rashmil-1999** [comment]
I see that we have the table and chart option as well. Are you planning to work on it further? or are you planning to work on it in separate issues? If so could you please also open issues for those tasks?

**Comment by longshuicy** [comment]
> I see that we have the table and chart option as well. Are you planning to work on it further? or are you planning to work on it in separate issues? If so could you please also open issues for those tasks?

I'll open issues for those but I don't plan to work on them for the first beta release. I think I will move on to work on "create project", and "add dfr3/hazard/dataset" to project as they seem more urgent.

**Comment by Rashmil-1999** [comment]
Yep! just what I was thinking hahaha.. you sensed my thought it seems :P

**Review by Rashmil-1999 — APPROVED** [review]
Looks good :D Approved!

**Pull request merged**
