### PR TITLE
Add github action

### LINKED ISSUE #2: Add Github Actions
Add Github actions for:

```[tasklist]
### Tasks
- [ ] Add Docker build similar to IN-CORE UI
- [ ] Add linting checks.
- [ ] Also add a good readme
- [ ] (add other things that I might have missed)
```

### PR DESCRIPTION
**Pull request by ywkim312**

### CODE REVIEW

**Comment by Rashmil-1999** [comment]
For this project we need node >=16. Maybe it is failing because of that. Could you please try removing the matrix and just keep node >= 16?

**Comment by Rashmil-1999** [comment]
As for docker, I think it is because this is a private repository. Do you have any ideas as to how we can tackle that?

**Review by Rashmil-1999 — APPROVED** [review]

**Comment by Rashmil-1999** [comment]
can you just add a changelog?

**Comment by ywkim312** [comment]
> can you just add a changelog?

Updated. I will merge it. Thanks

**Comment by Rashmil-1999** [comment]
Merging this...

**Pull request merged**
